spring:
  application:
    name: acorn_server
  profiles:
    include: ${include}
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: ${driverClassName}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9099

# MyBatis 설정 (주석 처리됨)
# mybatis:
#   mapper-locations: classpath:mybatis/mappers/*.xml